### ISSUE TITLE
Update css for color contrast accessibility

### ISSUE THREAD

**Issue by AmericanIris** [NYULibraries/ares-templates#1]
CSS change for /a11y/dist/css element color

`.instructor-table tbody tr.row-hover, .instructor-table tbody tr:hover, .student-table tbody tr.row-hover, .student-table tbody tr:hover {
    background-color: #E0D5E8;`

to

`#F3E8FB` for a 4.9:1 ratio for contrast at 18pt and 14pt

**Comment by AmericanIris** [comment]
Update the hover text color for header search submit button to `#22272D` . Text currently displays as `#FFFFFF` on `#E0D5E8` background (1.4:1) contrast. 

```
input.f-submit:hover, button.f-submit:hover, #search input.f-submit:hover, table.student-table tfoot input:hover {
    background-color: #E0D5E8;
    cursor: pointer;
    border-bottom: 2px #E0D5E8 solid;
    border-right: 2px #E0D5E8 solid;
    border-top: 2px #57068C solid;
    border-left: 2px #57068C solid;
}
```

**Comment by barnabyalter** [comment]
Done.
